name: Master Protection
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2.4.0

      - name: Check Tag
        run: |
          stringContain() { [ -z "$1" ] || { [ -z "${2##*$1*}" ] && [ -n "$2" ];};}
          if stringContain ${{github.head_ref}} 'staging' || stringContain ${{github.head_ref}} 'hotfix'; then  exit 0; else  exit 1; fi


